### ISSUE TITLE
combine seperate features 

### ISSUE THREAD

**Issue by mkeyno** [villamany/3dpBurner-sender#1]
hi sorry to open ticket for my question, but I wondering  whether you  maintain this repo any more but if you do please have look at this [link](https://github.com/arkypita/LaserGRBL/issues/29)
BR

**Comment by villamany** [comment]
Hi, mkeyno.
I looked the link. But for the moment there is no plan to implement that function. The 3dpSender goal is to be a simple application for sending the .gcode to 3dpBurner. 
Different laser power/speeds for each layer is the essential job of the CAM programs, they transforms all your needs into a .gcode file then you can send this file with the Sender (i use CamBam for generating the .gcode).

Thanks for the feedback.
