### ISSUE TITLE
Not so much an Issue, but a little utility I put together 

### ISSUE THREAD

**Issue by Nate-Bro** [villamany/3dpBurner-sender#2]
I just put together a little laser and I must say this project is great!

Your Image to Image2Gcode is great, but I also wanted to use a program I have been using for my CNC machine f-engrave [https://github.com/stephenhouser/f-engrave](url).

I made a little perl script to convert the z axis to spindle control, so it can do line drawings also.

I would have used C but I'm not that great in C.

[LC.zip](https://github.com/villamany/3dpBurner-sender/files/1033884/LC.zip)

**Comment by villamany** [comment]
Thanks for the ti Nate-Bro
